//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatManagerService.ChatEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class ChatDbContext : DbContext
    {
        public ChatDbContext()
            : base("name=ChatManagerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<tbl_User>().Property(u => u.Username).HasMaxLength(100);
            modelBuilder.Entity<tbl_User>().Property(u => u.Password).HasMaxLength(100);
            modelBuilder.Entity<tbl_User>().Property(u => u.Salt).HasMaxLength(100);
        }
    
        public DbSet<tbl_User> tbl_User { get; set; }
    }
}
